version: '3.3'
services:
  web:
    image: licence-code-generator
    ports:
      - "8081:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=super_secret_password
      - SETUP_ADMIN_USERNAME=super_secret_username
      - SETUP_ADMIN_EMAIL=super_secret_email
      - SETUP_ADMIN_PASSWORD=super_secret_password
      - SPRING_MAIL_USERNAME=super_secret_email
      - SPRING_MAIL_PASSWORD=super_secret_email_password
    depends_on:
      - postgres
    volumes:
      - logs:/home/logs
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secret_password
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
  logs: