apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops-tools
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32001
  selector:
    app: postgres